name: linux_client_builds
run-name: "Build Linux C++ Clients"
on: [push, workflow_dispatch]
permissions:
  packages: write

env:
  # Not sure this will work
  GH_PACKAGES_USERNAME: ${{ github.repository_owner }}
  GH_PACKAGES_FEED: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
  DHINSTALL: ${{ github.workspace }}/dhinstall

jobs:
  linux_job:
    name: Build C++ linux clients or fetch from cache
    runs-on: ubuntu-24.04

    steps:
      - name: Check out this repo
        uses: actions/checkout@v6

      - name: Try to restore (or begin the creation of) the cached installation directory
        id: cache-cpp-install
        uses: actions/cache@v5
        with:
          path: ${{ env.DHINSTALL }}
          key: ${{ runner.os }}-cpp-client-${{ hashfiles('cpp-client/**', 'proto/**') }}

      - name: Check out vcpkg
        id: checkout-vcpkg
        if: steps.cache-cpp-install.outputs.cache-hit != 'true'
        uses: actions/checkout@v6
        with:
          repository: microsoft/vcpkg
          path: vcpkg

      - name: Bootstrap vcpkg
        shell: bash
        if: steps.cache-cpp-install.outputs.cache-hit != 'true'
        run: ${{ github.workspace }}/vcpkg/bootstrap-vcpkg.sh

      - name: Get mono
        shell: bash
        if: steps.cache-cpp-install.outputs.cache-hit != 'true'
        run: sudo apt install mono-complete

      - name: Configure nuget to know how to download (or upload) each cached package that we need (or create)
        if: steps.cache-cpp-install.outputs.cache-hit != 'true'
        shell: bash
        run: |
          vcpkg_exe=${{ github.workspace }}/vcpkg/vcpkg
          echo $vcpkg_exe
          nuget_exe=mono `$vcpkg_exe fetch nuget | tail -n 1`
          echo $nuget_exe
          $nuget_exe \
            sources add \
            -Source "${{ env.GH_PACKAGES_FEED }}" \
            -StorePasswordInClearText \
            -Name GitHubPackages \
            -UserName "${{ env.GH_PACKAGES_USERNAME }}" \
            -Password "${{ secrets.GITHUB_TOKEN }}"
          $nuget_exe \
            setapikey "${{ secrets.GITHUB_TOKEN }}" \
            -Source "${{ env.FEED_URL }}"
