name: "Build .NET Client on Ubuntu 24.04"
run-name: "Build .NET Client on Ubuntu 24.04"
on: [push, workflow_dispatch]
permissions:
  packages: write

env:
  GH_PACKAGES_USERNAME: ${{ github.repository_owner }}
  GH_PACKAGES_FEED: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
  DHINSTALL: ${{ github.workspace }}/dhinstall

jobs:
  #=============================================================================
  # Identify DEEPHAVEN_VERSION
  #=============================================================================
  version_job:
    uses: ./.github/workflows/deephaven-version.yml
    
  #=============================================================================
  # Build the .NET Client
  #=============================================================================
  dotnet_job:
    name: Build .NET client on Ubuntu
    runs-on: ubuntu-24.04
    needs: version_job
    defaults:
      run:
        shell: bash

    steps:
      - name: Check out this repo
        uses: actions/checkout@v6

      - name: Setup dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Reveal Deephaven version
        env:
          DHC_VERSION: ${{ needs.version_job.outputs.dhc_version }}
        run: Hello, DHC version is ${{ env.DHC_VERSION }}

      - name: Build Deephaven Core C# Client
        run: |
          cd csharp/client/Dh_NetClient
          dotnet build -c Release
