name: kosak-win
run-name: "Will it blend v13: too many cooks"
on: [push, workflow_dispatch]

env:
  GH_PACKAGES_USERNAME: kosak
  GH_PACKAGES_FEED: https://nuget.pkg.github.com/kosak/index.json  

jobs:
  cpp_job:
    name: Build C++ client and let's do Python too
    runs-on: windows-2025

    steps:
      - name: Check out this repo
        uses: actions/checkout@v5

      - name: Check out vcpkg
        uses: actions/checkout@v5
        with:
          repository: microsoft/vcpkg
          path: vcpkg

      - name: Bootstrap vcpkg
        shell: cmd
        run: ./vcpkg/bootstrap-vcpkg.bat

      - name: Add Github NuGet caches (source/sink) for vcpkg
        shell: pwsh
        run: |
          $nuget_exe = & ./vcpkg/vcpkg.exe fetch nuget
          & $nuget_exe sources add `
          -Source "${{ env.GH_PACKAGES_FEED }}" `
          -StorePasswordInClearText `
          -Name GitHubPackages `
          -UserName "${{ env.GH_PACKAGES_USERNAME }}" `
          -Password "${{ secrets.GH_PACKAGES_TOKEN }}"
          & $nuget_exe setapikey "${{ secrets.GH_PACKAGES_TOKEN }}" -Source "${{ env.GH_PACKAGES_FEED }}"
        
      - name: Run cmake configuration
        shell: cmd
        env:
          VCPKG_BINARY_SOURCES: "clear;nuget,${{ env.GH_PACKAGES_FEED }},readwrite"
        run: cmake -S cpp-client/deephaven -B cpp-client/deephaven/build --toolchain ${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/dhinstall -DX_VCPKG_APPLOCAL_DEPS_INSTALL=ON

      - name: Run cmake build
        shell: cmd
        run: cmake --build cpp-client/deephaven/build --config RelWithDebInfo --target install

  version_job:
    name: Find the Deephaven version (separate job because it takes 45 seconds)
    runs-on: ubuntu-24.04
    outputs:
      dhc_version: ${{ steps.get-dhc-version.outputs.dhc_version }}

    steps:
      - name: Check out this repo
        uses: actions/checkout@v5

      - name: Setup JDK 11
        id: setup-java-11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Set JAVA_HOME
        run: echo "JAVA_HOME=${{ steps.setup-java-11.outputs.path }}" >> $GITHUB_ENV

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Output Deephaven Version
        id: get-dhc-version
        run: |
          ./gradlew :outputVersion
          cat build/version
          echo "dhc_version=$(cat build/version)" >> $GITHUB_OUTPUT

  echo_job:
    name: echo the Deephaven version (sad)
    runs-on: windows-2025
    needs: version_job
    steps:
      - run: echo "hello the version is ${{ needs.version_job.outputs.dhc_version }}"

  python_static:
    name: Python static client and maybe also ticking client
    needs:
    - cpp_job
    - version_job

    steps:
      - name: Check out this repo
        uses: actions/checkout@v5

    steps:
      - name: Get the C++ build
        run: echo get the build please

    steps:
      - name: Set common variables
        run: echo "DHINSTALL=${{ github.workspace }}/dhinstall" >> $GITHUB_ENV

    step:
      - name: Create the Python venv
        run: python3 -m venv "${{ github.workspace }}/cython-venv"
