name: kosak-win
run-name: "Will it blend v43: you didn't have a DEEPHAVEN_VERSION"
on: [push, workflow_dispatch]

env:
  GH_PACKAGES_USERNAME: kosak
  GH_PACKAGES_FEED: https://nuget.pkg.github.com/kosak/index.json
  DHINSTALL: ${{ github.workspace }}/dhinstall

jobs:
  cpp_job:
    name: Build C++ client
    runs-on: windows-2025

    steps:
      - name: Check out this repo
        uses: actions/checkout@v5

      - name: Cache the installation directory
        id: cache-cpp-install
        uses: actions/cache@v4
        with:
          path: ${{ env.DHINSTALL }}
          key: ${{ runner.os }}-cpp-client-${{ hashfiles('cpp-client/**', 'proto/**') }}

      - name: Check out vcpkg
        if: steps.cache-cpp-install.outputs.cache-hit != 'true'
        uses: actions/checkout@v5
        with:
          repository: microsoft/vcpkg
          path: vcpkg

      - name: Bootstrap vcpkg
        if: steps.cache-cpp-install.outputs.cache-hit != 'true'
        shell: cmd
        run: ./vcpkg/bootstrap-vcpkg.bat

      - name: Add Github NuGet caches (source/sink) for vcpkg
        if: steps.cache-cpp-install.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          $nuget_exe = & ./vcpkg/vcpkg.exe fetch nuget
          & $nuget_exe sources add `
          -Source "${{ env.GH_PACKAGES_FEED }}" `
          -StorePasswordInClearText `
          -Name GitHubPackages `
          -UserName "${{ env.GH_PACKAGES_USERNAME }}" `
          -Password "${{ secrets.GH_PACKAGES_TOKEN }}"
          & $nuget_exe setapikey "${{ secrets.GH_PACKAGES_TOKEN }}" -Source "${{ env.GH_PACKAGES_FEED }}"

      - name: Run cmake configuration
        if: steps.cache-cpp-install.outputs.cache-hit != 'true'
        shell: cmd
        env:
          VCPKG_BINARY_SOURCES: "clear;nuget,${{ env.GH_PACKAGES_FEED }},readwrite"
        run: cmake -S cpp-client/deephaven -B cpp-client/deephaven/build --toolchain ${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_INSTALL_PREFIX=${{ env.DHINSTALL }} -DX_VCPKG_APPLOCAL_DEPS_INSTALL=ON

      - name: Run cmake build
        if: steps.cache-cpp-install.outputs.cache-hit != 'true'
        shell: cmd
        run: cmake --build cpp-client/deephaven/build --config RelWithDebInfo --target install

      - name: Upload install directory as build artifact
        uses: actions/upload-artifact@v4
        with:
          name: cpp-client-install
          path: ${{ env.DHINSTALL }}

  version_job:
    name: Find the Deephaven version by grepping gradle.properties
    runs-on: ubuntu-24.04
    outputs:
      dhc_version: ${{ steps.get-dhc-version.outputs.dhc_version }}

    steps:
      - name: Check out this repo
        uses: actions/checkout@v5

      - name: Output Deephaven Version
        id: get-dhc-version
        run: |
          echo "dhc_version=$(grep ^deephavenBaseVersion= gradle.properties | cut -d'=' -f2)-$(grep ^deephavenBaseQualifier= gradle.properties | cut -d'=' -f2)" >> $GITHUB_OUTPUT

  echo_job:
    name: echo the Deephaven version (not sad)
    runs-on: windows-2025
    needs: version_job
    env:
      DEEPHAVEN_VERSION: ${{ needs.version_job.outputs.dhc_version }}
    steps:
      - run: echo "hello the version is ${{ needs.version_job.outputs.dhc_version }}"
      - run:
        shell: cmd
        steps: echo %DEEPHAVEN_VERSION%

  python_static_job:
    name: Python static client and maybe also ticking client
    needs: [cpp_job, version_job]
    runs-on: windows-2025

    steps:
      - name: Check out this repo
        uses: actions/checkout@v5

      - name: Get the C++ installation as a build artifact
        uses: actions/download-artifact@v4
        with:
          name: cpp-client-install
          path: ${{ env.DHINSTALL }}

      - name: Give me some Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install wheel
        shell: cmd
        run: pip3 install wheel

      - name: Install requirements
        shell: cmd
        run: |
          cd .\py\client
          pip3 install -r requirements-dev.txt

      - name: Running setup.py
        shell: cmd
        env:
          DEEPHAVEN_VERSION: ${{ needs.version_job.outputs.dhc_version }}
        run: |
          cd .\py\client
          python setup.py bdist_wheel

      - name: Do I have a wheel in this location? Try to upload it.
        shell: cmd
        run: |
          dir .\py\client\dist

  corey_fun_times:
    name: Corey fun times
    runs-on: windows-2025

    steps:
      - name: echo the thing
        run: echo are these the same $env:XYZINSTALL and also ${{ github.workspace }}/dhinstall blah bye $env:DHINSTALL zap

      - name: cmd shell too
        shell: cmd
        run: echo %DHINSTALL%
