name: kosak-win
run-name: "Will it blend v8: call it working for C++, starting on Python"
on: [push, workflow_dispatch]

jobs:
  job:
    name: Build C++ client and let's do Python too
    runs-on: windows-2025

    steps:
      - name: Check out this repo
        uses: actions/checkout@v5

      - name: Check out vcpkg
        uses: actions/checkout@v5
        with:
          repository: microsoft/vcpkg
          path: vcpkg

      - name: Bootstrap vcpkg
        shell: cmd
        run: ./vcpkg/bootstrap-vcpkg.bat

      - name: Add Github NuGet caches (source/sink) for vcpkg
        shell: pwsh
        env:
          USERNAME: kosak
          FEED_URL: https://nuget.pkg.github.com/kosak/index.json
        run: |
          $nuget_exe = & ./vcpkg/vcpkg.exe fetch nuget
          & $nuget_exe sources add `
          -Source "${{ env.FEED_URL }}" `
          -StorePasswordInClearText `
          -Name GitHubPackages `
          -UserName "${{ env.USERNAME }}" `
          -Password "${{ secrets.GH_PACKAGES_TOKEN }}"
          & $nuget_exe setapikey "${{ secrets.GH_PACKAGES_TOKEN }}" -Source "${{ env.FEED_URL }}"
        
      - name: Run cmake configuration
        shell: cmd
        run: cmake -S cpp-client/deephaven -B cpp-client/deephaven/build --toolchain ${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/dhinstall -DX_VCPKG_APPLOCAL_DEPS_INSTALL=ON
        env:
          VCPKG_BINARY_SOURCES: "clear;nuget,https://nuget.pkg.github.com/kosak/index.json,readwrite"

      - name: Run cmake build
        shell: cmd
        run: cmake --build cpp-client/deephaven/build --config RelWithDebInfo --target install
